version: "3.9"

services:
  zeebe:
    image: camunda/zeebe:latest
    container_name: zeebe
    environment:
      - ZEEBE_LOG_LEVEL=info
      - ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE=none
    ports:
      - "26500:26500"   # gRPC
      - "8080:8080"     # optional REST API (depending on image)
    networks:
      - loanflow-net

  operate:
    image: camunda/operate:latest
    container_name: operate
    environment:
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
    ports:
      - "8081:8080"
    depends_on:
      - zeebe
    networks:
      - loanflow-net

  tasklist:
    image: camunda/tasklist:latest
    container_name: tasklist
    environment:
      - CAMUNDA_TASKLIST_ZEEBE_GATEWAYADDRESS=zeebe:26500
    ports:
      - "8082:8080"
    depends_on:
      - zeebe
    networks:
      - loanflow-net

networks:
  loanflow-net:
    driver: bridge